import json
from pathlib import Path

import pytest


GIELLA_LEXICAL = Path("data/imported/giellalt/lexical_candidates.jsonl")
GIELLA_GRAMMAR = Path("data/imported/giellalt/grammar_candidates.jsonl")
SLS_RULES = Path("data/imported/sls/rule_candidates.jsonl")
CANDIDATE_PATHS = (GIELLA_LEXICAL, GIELLA_GRAMMAR, SLS_RULES)
AUDITED_GIELLA_LEXICAL_TYPES = {"noun", "verb", "numeral", "adjective"}


def _rows(path: Path):
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


@pytest.mark.parametrize("path", CANDIDATE_PATHS)
def test_generated_external_candidates_remain_non_promoting(path):
    if not path.exists():
        pytest.skip("candidate dataset is generated by refresh workflow")

    rows = _rows(path)
    assert rows, f"expected generated candidates in {path}"
    for row in rows:
        assert row["promotion_allowed"] is False
        assert row["source_commit"]
        assert row["source_path"]
        assert row["status"].startswith("external_candidate")


def test_giellalt_generated_lexical_candidates_have_only_audited_types():
    if not GIELLA_LEXICAL.exists():
        pytest.skip("GiellaLT lexical dataset is generated by refresh workflow")
    observed = {row["record_type"] for row in _rows(GIELLA_LEXICAL)}
    assert observed <= AUDITED_GIELLA_LEXICAL_TYPES


def test_giellalt_generated_adjectives_remain_external_candidates():
    if not GIELLA_LEXICAL.exists():
        pytest.skip("GiellaLT lexical dataset is generated by refresh workflow")
    adjectives = [row for row in _rows(GIELLA_LEXICAL) if row["record_type"] == "adjective"]
    if not adjectives:
        pytest.skip("adjective candidates appear after the next external refresh")
    assert all(row["promotion_allowed"] is False for row in adjectives)
    assert all(row["source_path"].endswith("adjectives.lexc") for row in adjectives)
    assert all("+" not in row["lemma"] for row in adjectives)


def test_giellalt_generated_grammar_candidates_are_review_gated():
    if not GIELLA_GRAMMAR.exists():
        pytest.skip("GiellaLT grammar dataset is generated by refresh workflow")
    rows = _rows(GIELLA_GRAMMAR)
    assert {row["record_type"] for row in rows} <= {"pronoun", "function_particle", "adposition"}
    assert all(row["usage_requires_review"] is True for row in rows)


def test_sls_generated_candidates_have_numbered_rules():
    if not SLS_RULES.exists():
        pytest.skip("SLS candidate dataset is generated by refresh workflow")
    assert all(row["rule_id"] and row["statement"] for row in _rows(SLS_RULES))
