import json
from pathlib import Path

import pytest


CANDIDATE_PATHS = (
    Path("data/imported/giellalt/lexical_candidates.jsonl"),
    Path("data/imported/sls/rule_candidates.jsonl"),
)


@pytest.mark.parametrize("path", CANDIDATE_PATHS)
def test_generated_external_candidates_remain_non_promoting(path):
    if not path.exists():
        pytest.skip("candidate dataset is generated by refresh workflow")

    rows = [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    assert rows, f"expected generated candidates in {path}"
    for row in rows:
        assert row["promotion_allowed"] is False
        assert row["source_commit"]
        assert row["source_path"]
        assert row["status"].startswith("external_candidate")


def test_giellalt_generated_candidates_have_audited_types():
    path = CANDIDATE_PATHS[0]
    if not path.exists():
        pytest.skip("GiellaLT candidate dataset is generated by refresh workflow")
    rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    assert {row["record_type"] for row in rows} <= {"noun", "verb", "numeral"}


def test_sls_generated_candidates_have_numbered_rules():
    path = CANDIDATE_PATHS[1]
    if not path.exists():
        pytest.skip("SLS candidate dataset is generated by refresh workflow")
    rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    assert all(row["rule_id"] and row["statement"] for row in rows)
